text_regex = '[a-zA-Z0-9,;\.\'\- ]+\.\n'
sentence_regex = '[a-zA-Z0-9,;\'\- ]+\.'
question_regex = '[a-zA-Z0-9,;\'\- ]+\?'
sentence_stop_regex = '\..'
question_stop_regex = '\?.'
text_stop_regex = '\n.'
character_regex = '([A-Z][a-z]*\s*)+'